server:
  port: 8080
  ssl:
    keyStore: ${SSL_KEYSTORE:}
    keyStorePassword: ${SSL_KEYSTORE_PASSWORD:}

solon:
  app:
    name: 'XiaomiAlbumSyncer'
    group: 'com.coooolfan'
    db: './db/xiaomialbumsyncer.db'
    jimmer-log: true
    webauthn:
      rpId: ${WEBAUTHN_RP_ID:localhost}
      rpName: ${WEBAUTHN_RP_NAME:XiaomiAlbumSyncer}
  logging:
    appender:
      console:
        level: INFO
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %-19(%cyan(%-19.19logger{0})) : %msg%n"
      file:
        level: INFO
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-25level %-19(%-19.19logger{0}): %msg%n"

sa-token:
  is-print: off
