server.port: 8080

solon.app:
  name: 'demo-app'
  group: 'demo'
  db: './db/xiaomialbumsyncer.db'
  jimmer-log: true

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO
