server:
  port: 8080

solon:
  app:
    name: 'XiaomiAlbumSyncer'
    group: 'com.coooolfan'
    db: './db/xiaomialbumsyncer.db'
    jimmer-log: false
  logging:
    appender:
      console:
        level: INFO
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %-18(%cyan(%-18.18logger{0})) : %msg%n"
      file:
        level: INFO
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-25level %-18(%-18.18logger{0}) : %msg%n"

sa-token:
  is-print: off
