name: Build Executable

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            arch: x64
          - os: windows-11-arm
            arch: arm64
          - os: ubuntu-22.04
            arch: x64
          - os: ubuntu-22.04-arm
            arch: arm64
          - os: macos-13
            arch: x64
          - os: macos-14
            arch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build for Unix-like systems
        if: runner.os != 'Windows'
        run: |
          pyinstaller --onefile --add-data "requirements.txt:." main.py
          chmod +x dist/main
          cp dist/main dist/XiaomiAlbumSyncer-v${{ github.event.release.tag_name }}-${{ matrix.os }}-${{ matrix.arch }}

      - name: Build for Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --add-data "requirements.txt;." main.py
          cp dist/main.exe dist/XiaomiAlbumSyncer-v${{ github.event.release.tag_name }}-${{ matrix.os }}-${{ matrix.arch }}.exe

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/XiaomiAlbumSyncer-v${{ github.event.release.tag_name }}-${{ matrix.os }}-${{ matrix.arch }}*
